apiVersion: v1
kind: Pod
metadata:
  name: discoveryservice-pod
  labels: 
    name: discoveryservice-pod
    app: discoveryservice
  
  spec:
    containers:
    - name: discoveryservice
      image: codyneal/discoveryservice
      ports:
      - containerPort: 8761

